export interface DispatchRecord {
  id: number;
  tripRate: string;
  date: string;
  client: string;
  driver: string;
  helper: string;
  unit: string;
  plateNo: string;
  ruta: string;
  bookingDr: string;
  noOfDrops: number;
  status: "Completed" | "In Transit" | "Pending";
  bookedBy: string;
}

export const MOCK_RECORDS: DispatchRecord[] = [
  {
    id: 1,
    date: "2025-05-01",
    client: "Flash Express",
    driver: "Alvin Paluga",
    helper: "Chester Evasco",
    unit: "Alawa Trucking",
    plateNo: "ABC 1234",
    ruta: "Manila – Laguna",
    bookingDr: "FE-2025-0001",
    noOfDrops: 5,
    status: "Completed",
    bookedBy: "Admin User",
    tripRate: "₱15,000",
  },
  {
    id: 2,
    date: "2025-05-02",
    client: "IPI",
    driver: "Noel Asumbrado",
    helper: "Ramil Diana",
    unit: "Gerald Roco",
    plateNo: "XYZ 5678",
    ruta: "Quezon City – Cavite",
    bookingDr: "IPI-2025-0042",
    noOfDrops: 6,
    status: "Completed",
    bookedBy: "Sarah Jenkins",
    tripRate: "₱12,500",
  },
  {
    id: 3,
    date: "2025-05-03",
    client: "Inteluck Corp",
    driver: "Ricky Pantua",
    helper: "No Helper",
    unit: "Kris Domingo",
    plateNo: "LMN 9012",
    ruta: "Pasig – Batangas",
    bookingDr: "IC-2025-0087",
    noOfDrops: 3,
    status: "In Transit",
    bookedBy: "Mike Ross",
    tripRate: "₱18,000",
  },
  {
    id: 4,
    date: "2025-05-04",
    client: "KTS Rentals",
    driver: "Gerald Roco",
    helper: "Jeric Juanico",
    unit: "Lito Diana",
    plateNo: "PQR 3456",
    ruta: "Makati – Pampanga",
    bookingDr: "KTS-2025-0015",
    noOfDrops: 2,
    status: "Completed",
    bookedBy: "Admin User",
    tripRate: "₱22,000",
  },
  {
    id: 5,
    date: "2025-05-05",
    client: "Transportify",
    driver: "Romano Ancheta",
    helper: "Richard Roda",
    unit: "Rochele Flores",
    plateNo: "DEF 7890",
    ruta: "Taguig – Bulacan",
    bookingDr: "TF-2025-0203",
    noOfDrops: 8,
    status: "Pending",
    bookedBy: "Jessica Pearson",
    tripRate: "₱14,000",
  },
  {
    id: 6,
    date: "2025-05-06",
    client: "XMD Logistics",
    driver: "Rommel Lumacang",
    helper: "Felipe Guban",
    unit: "Alawa Trucking",
    plateNo: "GHI 2345",
    ruta: "Valenzuela – Rizal",
    bookingDr: "XMD-2025-0098",
    noOfDrops: 5,
    status: "Completed",
    bookedBy: "Louis Litt",
    tripRate: "₱9,500",
  },
  {
    id: 7,
    date: "2025-05-07",
    client: "Urenholt",
    driver: "Jomarie Divina",
    helper: "Rizalito Domingo",
    unit: "Gerald Roco",
    plateNo: "JKL 6789",
    ruta: "Manila – Cebu (Sea)",
    bookingDr: "UR-2025-0011",
    noOfDrops: 1,
    status: "In Transit",
    bookedBy: "Donna Paulsen",
    tripRate: "₱45,000",
  },
  {
    id: 8,
    date: "2025-05-08",
    client: "Flash Express",
    driver: "Lim Ubal",
    helper: "Vince Marzonia",
    unit: "Kris Domingo",
    plateNo: "MNO 1357",
    ruta: "Caloocan – Laguna",
    bookingDr: "FE-2025-0009",
    noOfDrops: 7,
    status: "Completed",
    bookedBy: "Harvey Specter",
    tripRate: "₱16,500",
  },
  {
    id: 9,
    date: "2025-05-09",
    client: "IPI",
    driver: "Ever Bacvano",
    helper: "James Eric Manabo",
    unit: "Lito Diana",
    plateNo: "STU 2468",
    ruta: "Parañaque – Bataan",
    bookingDr: "IPI-2025-0055",
    noOfDrops: 4,
    status: "Pending",
    bookedBy: "Rachel Zane",
    tripRate: "₱25,000",
  },
  {
    id: 10,
    date: "2025-05-10",
    client: "Transportify",
    driver: "Edcel Ralo",
    helper: "No Helper",
    unit: "Rochele Flores",
    plateNo: "VWX 9753",
    ruta: "Mandaluyong – Nueva Ecija",
    bookingDr: "TF-2025-0214",
    noOfDrops: 3,
    status: "Completed",
    bookedBy: "Admin User",
    tripRate: "₱28,000",
  },
];